### PR TITLE
yolo: use moka future instead of sync to try and fix #181

### LINKED ISSUE #181: solver: occasionally 'gets stuck'
In testnet our solver occasionally reaches a state where it fails to process new transactions.
The logs are sparse, but on one such instance our RPC contained logs such as:
```
{"timestamp":"2025-10-21T15:59:08.882846Z","level":"ERROR","fields":{"message":"error trading","amount":"995000000000000000","src_chain_id":"84532","dest_chain_id":"43113","request_id":"0x161df51ae34430b57b1a91d9ccc9b02c98538e1381b0932c9b44579fb7e115cf","error":"server returned an error response: error code 3: execution reverted, data: \\"0xfb8f41b2000000000000000000000000c69dd549b037215ba1ea9866ffa59603862bf98600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000dcef33a6f838000\\""},"target":"onlyswaps_solver::executor"}
{"timestamp":"2025-10-21T15:59:40.212409Z","level":"INFO","fields":{"message":"executing trades ","chain_id":84532,"trade_count":1},"target":"onlyswaps_solver::app"}
{"timestamp":"2025-10-21T16:25:18.677575Z","level":"ERROR","fields":{"message":"WS connection error","err":"WebSocket protocol error: Connection reset without closing handshake"},"target":"alloy_transport_ws::native"}
{"timestamp":"2025-10-21T17:46:56.797174Z","level":"ERROR","fields":{"message":"WS connection error","err":"WebSocket protocol error: Connection reset without closing handshake"},"target":"alloy_transport_ws::native"}'
```

Some points to note:
- it initially got a revert when attempting a transaction
- it tried to execute another trade (probably the reverted one) 32s later
- the second execution never completes with success nor failure (we expect a log for both [success](https://github.com/randa-mu/dcipher/blob/3ba28928add5cd25ede8dc2f1593a25fb848a27d/bin/onlyswaps-solver/src/executor.rs#L104) and for [failure](https://github.com/randa-mu/dcipher/blob/3ba28928add5cd25ede8dc2f1593a25fb848a27d/bin/onlyswaps-solver/src/executor.rs#L106).
- the websocket drops are quite far apart, so presumably they're irrelevant

### PR DESCRIPTION
**Pull request by CluEleSsUK**

### CODE REVIEW

File: bin/onlyswaps-solver/src/executor.rs [hunk 1]
```diff
@@ -57,61 +60,71 @@ impl<'a, P: Provider> TradeExecutor<'a, P> {
...
-            match approve {
-                Ok(_) => {}
-                Err(e) => {
-                    tracing::error!(e = ?e,"error approving trade");
+            // and finally execute the trade with a timeout
+            match timeout(
+                Duration::from_secs(10),
+                execute_trade(&trade, router, token, self.own_address),
+            )
+            .await
```
Comment (azixus) [inline bin/onlyswaps-solver/src/executor.rs]: good idea to add the timeout at this level directly, don't have to individually instrument transactions.
